### ISSUE TITLE
Does not work when others are voting?

### ISSUE THREAD

**Issue by lilelduque23** [dado3212/PollDaddyHack#11]
When others are voting, I find I get a constant recall of "Voted (time number xxx)" into the thousands, but there is no actual movement in percentage.  I know it is possible to get multiple votes in either (1) no one else is voting and run the script (times out at 25 votes and repeat again after 70 second rest period) or (2) even with others voting, vote 25 with refreshes on a browser that doesn't save cookies (possible with multiple machines)

poll_id = 9599861
answer_id = 43865243

Any help or clarification is appreciated.  Thank you.

**Comment by dado3212** [comment]
This shouldn't be the case.  I haven't noticed it happening.  Unfortunately this response is obviously quite a bit later than when you asked the question, but if you have a more recent poll_id/answer_id combo, make a new issue.
