### ISSUE TITLE
Just getting sleep messages

### ISSUE THREAD

**Issue by belzaaron** [dado3212/PollDaddyHack#16]
Hi! I am trying to use this to test some things out for the future... I am trying to run this using Python 2.7 and have only changed the poll ID and answer ID, everything else remains constant. Should the IDs be strings? I am only receiving the "Locked" message.

I looked at some prior issues and have seen a trend whereas polls disallow multi-votes from the same IP. Though, then what is the proxy really doing? Or is there a way for me to check if the poll disables this?

Thanks!

**Comment by dado3212** [comment]
Is the poll that you were trying this on still open?  The "proxy" isn't actually changing your IP, just an attempt to mask where the votes are coming from.  I can look into adding a proper IP changing functionality with TorRequests, but I need a form to test with.

**Comment by belzaaron** [comment]
Sadly no :( the form has since closed... I appreciate your response though :)
