### ISSUE TITLE
Mutiple question poll

### ISSUE THREAD

**Issue by kingsel** [dado3212/PollDaddyHack#18]
I used this code and it works perfectly, but I have been trying to use it for a poll which has mutiple questions, how can I edit the code to get it to work

**Comment by dado3212** [comment]
Can you comment the link to the poll so I can take a look?  You can also send me a message through my website's contact form, which is linked in my profile if you're not comfortable sharing it publicly.

**Comment by kingsel** [comment]
I am trying to send you a message through your website's contact form but it is not going through, can you write me your contact email directly so I send you the link or you can write to me on my email so I get your contact...this is my email
selasi.emperor@gmail.com

**Comment by kingsel** [comment]
I have finally been able to send you the link to the poll through ur mail.

**Comment by dado3212** [comment]
It's not really a direct change for multi-question posts.  For one, you need to get all of the question IDs and answer IDs from the page, which takes a while.  Additionally, the format of the request is different.  What I would recommend doing is a replay attack.  Use something like [Fiddler](https://www.telerik.com/download/fiddler), and go through filling out the form once normally on your computer with Fiddler open.  Then once you've hit submit, find the POST request that you made in Fiddler and replay it ('R' is the default shortcut, or right-click and choose 'Replay').  It's a little more manual, but doesn't require you to do a bunch of code.
