### ISSUE TITLE
proxy error

### ISSUE THREAD

**Issue by bellsands** [dado3212/PollDaddyHack#19]
Hello good day, 

I'm trying to use this code for a polldaddy, I already changed everything for the specific poll I want and It says vote but also proxy error. I installed conda and scrapy and still doesn't work. Is there anything else I should install in my computer in order to make that work?! or any other suggestions? Any help would be great as I don't understand much. 

Thanks.

**Comment by dado3212** [comment]
It just depends on requests, re, json, time, and random.
