### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by bastianvs** [dado3212/PollDaddyHack#9]
this is not working...

**Comment by GiVeMeRoOt** [comment]
I just tried it and it works like really good. It is a bit slow though. and don't forget to comment out line number 3.

**Comment by NicholasGertz** [comment]
@GiVeMeRoOt
even I comment out line number 3, I get the error: **Locked.  Sleeping for 60 seconds.**
Im using phyton 2.7.3. Is the a problem because its an https address? 

**its the following poll:**
poll_id = 9611451
answer_id = 43928310
number_of_votes = 1000

**Comment by dado3212** [comment]
This script will only work on polls that allow you to vote more than one time from the same IP.

**Comment by NicholasGertz** [comment]
thanks!
